config/routes.rb
Rails.application.routes.draw do
  resources :friends
  resources :life_rankings
  resources :life_pages
  resources :advertisements
  get 'ori_event_page/index'
  get 'ori_event_page/:id', to: 'ori_event_page#show'


  resources :ori_pages
  get 'unisna/index'
  get 'unisna/men/:id', to: 'unisna#men'
  get 'unisna/women/:id', to: 'unisna#women'

  resources :map_urls
  get 'dosihsha_ranks/index'

  get 'maps/kyotanabe'
  get 'maps/imadegawa'
  get 'maps/index'
  get 'maps/karasuma'
  get 'maps/kanbaikan'
  get 'maps/shinmachi'

  get 'advices/capacities'
  get 'advices/languages'
  get 'advices/words'
  get 'advices/exams'
  get 'advices/welcome'
  get 'advices/loves'
  get 'advices/life'
  get 'advices/friend'

  resources :women_snaps
  resources :men_snaps
  resources :fashion_ranks
  resources :trip_ranks
  resources :school_ranks
  resources :job_ranks
  resources :circle_ranks
  resources :exam_comments
  resources :exams
  resources :campus_ranks
  resources :campus_lives
  resources :capacities
  resources :date_places
  resources :loves
  resources :languages
  resources :words
  resources :university_words
  resources :introduce_university_words
  resources :sessions
  get 'adminpages/index'
  get 'advices/index'
  root to: 'home#index'
  get '*path', controller: 'application', action: 'render_404'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/campus_life.rb
class CampusLife < ApplicationRecord
  mount_uploader :campus_image1, CampusImage1Uploader
  mount_uploader :campus_image2, CampusImage2Uploader
end

app/models/campus_rank.rb
class CampusRank < ApplicationRecord
end

app/models/capacity.rb
class Capacity < ApplicationRecord
  mount_uploader :capa_image1, CapaImage1Uploader
  mount_uploader :capa_image2, CapaImage2Uploader
  mount_uploader :capa_image3, CapaImage3Uploader
  mount_uploader :capa_image4, CapaImage4Uploader
  mount_uploader :capa_image5, CapaImage5Uploader
  mount_uploader :capa_image6, CapaImage6Uploader
end

app/models/circle_rank.rb
class CircleRank < ApplicationRecord
end

app/models/date_place.rb
class DatePlace < ApplicationRecord
  mount_uploader :place_image, PlaceImageUploader
end

app/models/exam.rb
class Exam < ApplicationRecord
  mount_uploader :exam_image, ExamImageUploader
end

app/models/friend.rb
class Friend < ApplicationRecord
  mount_uploader :friend_photo1, FriendPhoto1Uploader
  mount_uploader :friend_photo2, FriendPhoto2Uploader
  mount_uploader :friend_photo3, FriendPhoto3Uploader
  mount_uploader :friend_photo4, FriendPhoto4Uploader
end

app/models/job_rank.rb
class JobRank < ApplicationRecord
end

app/models/language.rb
class Language < ApplicationRecord
  mount_uploader :image, ImageUploader
end

app/models/life_page.rb
class LifePage < ApplicationRecord
  mount_uploader :life_photo1, LifePhoto1Uploader
  mount_uploader :life_photo2, LifePhoto2Uploader
  mount_uploader :life_photo3, LifePhoto3Uploader
  mount_uploader :life_photo4, LifePhoto4Uploader
end

app/models/love.rb
class Love < ApplicationRecord
  mount_uploader :image1, Image1Uploader
  mount_uploader :image2, Image2Uploader
  mount_uploader :image3, Image3Uploader
  mount_uploader :image4, Image4Uploader
end

app/models/map_url.rb
class MapUrl < ApplicationRecord
end

app/models/men_snap.rb
class MenSnap < ApplicationRecord
  mount_uploader :men_image, MenImageUploader
  mount_uploader :men_image2, MenImage2Uploader
  mount_uploader :men_image3, MenImage3Uploader
end

app/models/ori_page.rb
class OriPage < ApplicationRecord
  mount_uploader :ori_photo1, OriPhoto1Uploader
  mount_uploader :ori_photo2, OriPhoto2Uploader
end

app/models/school_rank.rb
class SchoolRank < ApplicationRecord
end

app/models/trip_rank.rb
class TripRank < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password 
end

app/models/women_snap.rb
class WomenSnap < ApplicationRecord
  mount_uploader :women_image, WomenImageUploader
  mount_uploader :women_image2, WomenImage2Uploader
  mount_uploader :women_image3, WomenImage3Uploader
end

app/models/word.rb
class Word < ApplicationRecord
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  layout 'admin'
  before_action :login_check, only: %i(index new edit create update destroy)
  before_action :set_friend, only: [:show, :edit, :update, :destroy]

  # GET /friends
  # GET /friends.json
  def index
    @friends = Friend.all
  end

  # GET /friends/1
  # GET /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    @friend = Friend.new
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends
  # POST /friends.json
  def create
    @friend = Friend.new(friend_params)

    respond_to do |format|
      if @friend.save
        format.html { redirect_to friends_url, notice: 'Friend was successfully created.' }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1
  # PATCH/PUT /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to friends_url, notice: 'Friend was successfully updated.' }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1
  # DELETE /friends/1.json
  def destroy
    @friend.destroy
    respond_to do |format|
      format.html { redirect_to friends_url, notice: 'Friend was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end
    def login_check
      if session[:user_id].nil?
        redirect_to sessions_path
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def friend_params
      params.require(:friend).permit(:friend_photo1, :friend_photo2, :friend_photo3, :friend_photo4, :context)
    end
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/views/friends/_form.html.erb
<%= form_with(model: friend, local: true) do |form| %>
  <% if friend.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
      <% friend.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :friend_photo1 %>
    <%= form.text_field :friend_photo1, id: :friend_friend_photo1 %>
  </div>

  <div class="field">
    <%= form.label :friend_photo2 %>
    <%= form.text_field :friend_photo2, id: :friend_friend_photo2 %>
  </div>

  <div class="field">
    <%= form.label :friend_photo3 %>
    <%= form.text_field :friend_photo3, id: :friend_friend_photo3 %>
  </div>

  <div class="field">
    <%= form.label :friend_photo4 %>
    <%= form.text_field :friend_photo4, id: :friend_friend_photo4 %>
  </div>

  <div class="field">
    <%= form.label :context %>
    <%= form.text_area :context, id: :friend_context %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/friends/edit.html.erb
<div class="col-md-12">
  <h3>友達の作り方</h3>
</div>
<div>
  <%=form_for @friend do |f| %>
    <div class="col-md-6 adBox">
      <table class="table">
        <tr>
          <th scope="row">一言</th>
          <td><%= f.text_area :context, class: "form-control"%></td>
        </tr>
        <tr>
          <th scope="row">画像1</th>
          <td><%= f.file_field :friend_photo1%></td>
        </tr>
        <tr>
          <th scope="row">画像2</th>
          <td><%= f.file_field :friend_photo2%></td>
        </tr>
        <tr>
          <th scope="row">画像3</th>
          <td><%= f.file_field :friend_photo3 %></td>
        </tr>
        <tr>
          <th scope="row">画像4</th>
          <td><%= f.file_field :friend_photo4 %></td>
        </tr>
      </table>
      <%= f.submit "送信" ,class: "btn" %>
    </div>
  <% end %>
</div>

app/views/friends/index.html.erb
<div class="col-md-5 adBox">
    <h4>友達の作り方</h4>
    <% @friends.each do |friend| %>
      <table class="table">
        <tr>
          <th scope="row">ポイント</th>
          <td><%= friend.context %><span class="button"><%= link_to '削除',friend_path(friend.id),method: :delete%></span>
          <span class="button"><%= link_to '編集',edit_friend_path(friend.id)%></td>
        </tr>
        <tr>
          <th scope="row">画像1</th>
          <td><%= image_tag friend.friend_photo1,class: "resize" %></td>
        </tr>
        <tr>
          <th scope="row">画像2</th>
          <td><%= image_tag friend.friend_photo2,class: "resize" %></td>
        </tr>
        <tr>
          <th scope="row">画像3</th>
          <td><%= image_tag friend.friend_photo3,class: "resize" %></td>
        </tr>
        <tr>
          <th scope="row">画像4</th>
          <td><%= image_tag friend.friend_photo4,class: "resize" %></td>
        </tr>
      </table>
    <% end %>
    <%= link_to '新規作成', new_friend_path %>
  </div>

app/views/friends/new.html.erb
<div class="col-md-12">
  <h3>友達の作り方</h3>
</div>
<div>
  <%=form_for @friend do |f| %>
    <div class="col-md-6 adBox">
      <table class="table">
        <tr>
          <th scope="row">一言</th>
          <td><%= f.text_area :context, class: "form-control"%></td>
        </tr>
        <tr>
          <th scope="row">画像1</th>
          <td><%= f.file_field :friend_photo1%></td>
        </tr>
        <tr>
          <th scope="row">画像2</th>
          <td><%= f.file_field :friend_photo2%></td>
        </tr>
        <tr>
          <th scope="row">画像3</th>
          <td><%= f.file_field :friend_photo3 %></td>
        </tr>
        <tr>
          <th scope="row">画像4</th>
          <td><%= f.file_field :friend_photo4 %></td>
        </tr>
      </table>
      <%= f.submit "送信" ,class: "btn" %>
    </div>
  <% end %>
</div>

app/views/friends/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Friend photo1:</strong>
  <%= @friend.friend_photo1 %>
</p>

<p>
  <strong>Friend photo2:</strong>
  <%= @friend.friend_photo2 %>
</p>

<p>
  <strong>Friend photo3:</strong>
  <%= @friend.friend_photo3 %>
</p>

<p>
  <strong>Friend photo4:</strong>
  <%= @friend.friend_photo4 %>
</p>

<p>
  <strong>Context:</strong>
  <%= @friend.context %>
</p>

<%= link_to 'Edit', edit_friend_path(@friend) %> |
<%= link_to 'Back', friends_path %>