config/routes.rb
Rails.application.routes.draw do
  resources :friends
  resources :life_rankings
  resources :life_pages
  resources :advertisements
  get 'ori_event_page/index'
  get 'ori_event_page/:id', to: 'ori_event_page#show'


  resources :ori_pages
  get 'unisna/index'
  get 'unisna/men/:id', to: 'unisna#men'
  get 'unisna/women/:id', to: 'unisna#women'

  resources :map_urls
  get 'dosihsha_ranks/index'

  get 'maps/kyotanabe'
  get 'maps/imadegawa'
  get 'maps/index'
  get 'maps/karasuma'
  get 'maps/kanbaikan'
  get 'maps/shinmachi'

  get 'advices/capacities'
  get 'advices/languages'
  get 'advices/words'
  get 'advices/exams'
  get 'advices/welcome'
  get 'advices/loves'
  get 'advices/life'
  get 'advices/friend'

  resources :women_snaps
  resources :men_snaps
  resources :fashion_ranks
  resources :trip_ranks
  resources :school_ranks
  resources :job_ranks
  resources :circle_ranks
  resources :exam_comments
  resources :exams
  resources :campus_ranks
  resources :campus_lives
  resources :capacities
  resources :date_places
  resources :loves
  resources :languages
  resources :words
  resources :university_words
  resources :introduce_university_words
  resources :sessions
  get 'adminpages/index'
  get 'advices/index'
  root to: 'home#index'
  get '*path', controller: 'application', action: 'render_404'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/campus_life.rb
class CampusLife < ApplicationRecord
  mount_uploader :campus_image1, CampusImage1Uploader
  mount_uploader :campus_image2, CampusImage2Uploader
end

app/models/campus_rank.rb
class CampusRank < ApplicationRecord
end

app/models/capacity.rb
class Capacity < ApplicationRecord
  mount_uploader :capa_image1, CapaImage1Uploader
  mount_uploader :capa_image2, CapaImage2Uploader
  mount_uploader :capa_image3, CapaImage3Uploader
  mount_uploader :capa_image4, CapaImage4Uploader
  mount_uploader :capa_image5, CapaImage5Uploader
  mount_uploader :capa_image6, CapaImage6Uploader
end

app/models/circle_rank.rb
class CircleRank < ApplicationRecord
end

app/models/date_place.rb
class DatePlace < ApplicationRecord
  mount_uploader :place_image, PlaceImageUploader
end

app/models/exam.rb
class Exam < ApplicationRecord
  mount_uploader :exam_image, ExamImageUploader
end

app/models/friend.rb
class Friend < ApplicationRecord
  mount_uploader :friend_photo1, FriendPhoto1Uploader
  mount_uploader :friend_photo2, FriendPhoto2Uploader
  mount_uploader :friend_photo3, FriendPhoto3Uploader
  mount_uploader :friend_photo4, FriendPhoto4Uploader
end

app/models/job_rank.rb
class JobRank < ApplicationRecord
end

app/models/language.rb
class Language < ApplicationRecord
  mount_uploader :image, ImageUploader
end

app/models/life_page.rb
class LifePage < ApplicationRecord
  mount_uploader :life_photo1, LifePhoto1Uploader
  mount_uploader :life_photo2, LifePhoto2Uploader
  mount_uploader :life_photo3, LifePhoto3Uploader
  mount_uploader :life_photo4, LifePhoto4Uploader
end

app/models/love.rb
class Love < ApplicationRecord
  mount_uploader :image1, Image1Uploader
  mount_uploader :image2, Image2Uploader
  mount_uploader :image3, Image3Uploader
  mount_uploader :image4, Image4Uploader
end

app/models/map_url.rb
class MapUrl < ApplicationRecord
end

app/models/men_snap.rb
class MenSnap < ApplicationRecord
  mount_uploader :men_image, MenImageUploader
  mount_uploader :men_image2, MenImage2Uploader
  mount_uploader :men_image3, MenImage3Uploader
end

app/models/ori_page.rb
class OriPage < ApplicationRecord
  mount_uploader :ori_photo1, OriPhoto1Uploader
  mount_uploader :ori_photo2, OriPhoto2Uploader
end

app/models/school_rank.rb
class SchoolRank < ApplicationRecord
end

app/models/trip_rank.rb
class TripRank < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password 
end

app/models/women_snap.rb
class WomenSnap < ApplicationRecord
  mount_uploader :women_image, WomenImageUploader
  mount_uploader :women_image2, WomenImage2Uploader
  mount_uploader :women_image3, WomenImage3Uploader
end

app/models/word.rb
class Word < ApplicationRecord
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController

  def index
  end
  def kyotanabe
  end

  def kanbaikan
  end
  def karasuma
  end
  def shinmachi
  end
  def imadegawa
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/views/maps/imadegawa.html.erb
<div id="kyotanabe">
    <div class="centerMap">
      <h1>今出川MAP</h1>
      <div class="kyotanabeMap">
        <%=image_tag('imade.png',class:"kyotanabe")%>
        <div class="building">
          <ul>
            <li>①博遠館</li>
            <li>②良心館</li>
            <ul>
              <li>
            　　良心館の食堂はお昼ご飯の時間には人がいっぱい。勉強したり、パソコンを使ったり、友達と話し合いができる場所がある。
            </li>
            </ul>
            <li>③寧静館</li>
            <li>④真義館</li>
            <li>⑤彰栄館</li>
            <li>⑥同志社礼拝堂</li>
            <li>⑦扶桑館</li>
            <li>⑧ハリス理化学館</li>
            <li>⑨至誠館</li>
            <li>⑩クラーク記念館</li>
            <li>⑪待辰館</li>
            <li>⑫神学館</li>
            <li>⑬図書館</li>
            <li>⑭明徳館</li>
            <ul>
            <li>
            　ラウンジや、おしゃれなカフェがある
            </li>
            </ul>
            <li>⑮徳照館</li>
            <li>⑯弘風館</li>
            <li>⑰有終館</li>
            <li>⑱到遠館</li>
          </ul>
        </div>
      </div>
    </div>
  </div>

app/views/maps/index.html.erb
<div class="maptitle">
  <div class="mapbox">
    <div class="mapTitle"><h5><%= link_to '今出川キャンパスMAP',maps_imadegawa_path,:style=>"text-decoration:none" %></h5></div>
    <div class="mapTitle"><%= link_to '京田辺キャンパスMAP',maps_kyotanabe_path,:style=>"text-decoration:none" %></div>
    <div class="mapTitle"><%= link_to '新町キャンパスMAP',maps_shinmachi_path,:style=>"text-decoration:none" %></div>
    <div class="mapTitle"><%= link_to '烏丸キャンパスMAP',maps_karasuma_path,:style=>"text-decoration:none"; %></div>
    <div class="mapTitle"><%= link_to '寒梅館',maps_kanbaikan_path,:style=>"text-decoration:none" %></div>
  </div>
</div>

app/views/maps/kanbaikan.html.erb
<div id="kyotanabe">
    <div class="centerMap">
      <h1>寒梅館MAP</h1>
      <div class="kyotanabeMap">
        <%=image_tag('kanbaikan.png',class:"kyotanabe")%>
        <div class="building">
        <ul>
          <li>①寒梅館</li>
  　<ul><li>保健センターやホールがある。
  　ここのパフェが人気</li></ul>
        </ul>
      </div>

      </div>
    </div>
  </div>

app/views/maps/karasuma.html.erb
<div id="kyotanabe">
    <div class="centerMap">
      <h1>烏丸キャンパスMAP</h1>
      <div class="kyotanabeMap">
        <%=image_tag('karasuma.png',class:"kyotanabe")%>
        <div class="building">
        <ul>
          <li>①志高館</li>
　<ul><li>保健センターがある。</li></ul>
        </ul>
      </div>

      </div>
    </div>
  </div>

app/views/maps/kyotanabe.html.erb
<div id="kyotanabe">
    <div class="centerMap">
      <h1>京田辺キャンパスMAP</h1>
      <div class="kyotanabeMap">
        <%=image_tag('tanabe.png',class:"kyotanabe")%>
        <div class="building">
        <ul>
  <li>①京田辺別館</li>
  <ul>
    <li>
  　クラブやサークルなどのBOXがある。
    </li>
  </ul>
  <li>②知真館2号館</li>
  <li>③厚正館保健センター</li>
  <li>④知真館1号館</li>
  <li>⑤知真館3号館</li>
  <li>⑥日糧館</li>
  <ul>
    <li>
  　食堂専門街、本屋さんなどお店がたくさんある。
  </li>
  </ul>
  <li>⑦成心館</li>
  <li>⑧ハローホール（多目的ホール）</li>
  <ul>
    <li>
  　文化イベント用の建物で、ホール前広場では、ライブコンサートや応援団による演舞と
  いった様々がイベントを開催できる。
  </li>
  </ul>
  <li>⑨頷真館</li>
  <li>⑩恵道館</li>
  <li>⑪ラードネット記念図書館</li>
  <li>⑫嗣業館</li>
  <li>⑬交隣館</li>
  <li>⑭光喜館</li>
  <li>⑮恵喜館</li>
  <li>⑯紫苑館</li>
  <ul>
    <li>
  　食堂やラウンジがある。
  </li>
  </ul>
  <li>⑰新島記念講堂（礼拝堂）</li>
  <li>⑱同志社ローム記念館</li>
  <li>⑲夢告館</li>
  <li>⑳光館</li>
  <li>㉑情報メディア館</li>
  <li>㉒知証館南館　電気系実験実習室</li>
  <li>㉓知証館北館　機械系実験実習棟</li>
  <li>㉔知証館南館　心理学実験室</li>
  <li>㉕知証館北館　機械実習工場　</li>
  <li>㉖知証館北館　実習工場別棟</li>
  <li>㉗光館</li>
  <li>㉘言館</li>
  <li>㉙香伯館</li>
  <ul>
    <li>
  　心理学部・心理学研究科とグローバル・コミュニケーション学部の拠点施設
  </li>
  </ul>
  <li>㉚知源館</li>
  <li>㉛至心館</li>
  <li>㉜澄明館</li>
  <li>㉝有徳館西館</li>
  <li>㉞有徳館東館</li>
  <li>㉟創考館</li>
  <li>㊱理化学館</li>
  <li>㊳報辰館</li>
  <li>㊳香知館</li>

  <li>㊴医心館</li>
  <ul>
    <li>
  　生命医科学部・生命医科学研究科の拠点施設
  </li>
  </ul>
  <li>㊵デビィス記念館</li>
  <li>㊶プール</li>
  <li>㊷体育BOX棟</li>
  <li>㊸京田辺体育ハウス-２</li>
  <li>㊹京田辺体育ハウス-1</li>
  <li>㊺真誠館</li>
  <ul>
    <li>
  　相撲場、レスリング場、ボクシング場、空手道場、日本拳法場、少林寺拳法場、合気 道
  場、居合道場、トレーニング室を備えた体育施設がある。
  </li>
  </ul>
  <li>㊻磐上館</li>
  <ul>
    <li>
  　スポーツ健康科学部・スポーツ健康科学研究科の拠点施設
  </li>
  </ul>
  <li>㊼体育シャワー場</li>
        </ul>
      </div>
  </div>

      </div>
    </div>

app/views/maps/shinmachi.html.erb
<div id="kyotanabe">
    <div class="centerMap">
      <h1>新町キャンパスMAP</h1>
      <div class="kyotanabeMap">
        <%=image_tag('shinmachi.png',class:"kyotanabe")%>
        <div class="building">
        <ul>
          <li>①新町別館</li>
<li>②学生会館</li>
　<ul><li>クラブのやサークルなどのBOXがある</li></ul>
<li>③育真館</li>
　<ul><li>授業や体育会、スポーツ系のサークル活動で使う体育館。</li></ul>
<li>④尋真館</li>
<li>⑤臨光館</li>
<ul><li>
　社会学部と政策学部がよく使う
</li></ul>
</ul>
      </div>

      </div>
    </div>
  </div>