config/routes.rb
Rails.application.routes.draw do
  resources :friends
  resources :life_rankings
  resources :life_pages
  resources :advertisements
  get 'ori_event_page/index'
  get 'ori_event_page/:id', to: 'ori_event_page#show'


  resources :ori_pages
  get 'unisna/index'
  get 'unisna/men/:id', to: 'unisna#men'
  get 'unisna/women/:id', to: 'unisna#women'

  resources :map_urls
  get 'dosihsha_ranks/index'

  get 'maps/kyotanabe'
  get 'maps/imadegawa'
  get 'maps/index'
  get 'maps/karasuma'
  get 'maps/kanbaikan'
  get 'maps/shinmachi'

  get 'advices/capacities'
  get 'advices/languages'
  get 'advices/words'
  get 'advices/exams'
  get 'advices/welcome'
  get 'advices/loves'
  get 'advices/life'
  get 'advices/friend'

  resources :women_snaps
  resources :men_snaps
  resources :fashion_ranks
  resources :trip_ranks
  resources :school_ranks
  resources :job_ranks
  resources :circle_ranks
  resources :exam_comments
  resources :exams
  resources :campus_ranks
  resources :campus_lives
  resources :capacities
  resources :date_places
  resources :loves
  resources :languages
  resources :words
  resources :university_words
  resources :introduce_university_words
  resources :sessions
  get 'adminpages/index'
  get 'advices/index'
  root to: 'home#index'
  get '*path', controller: 'application', action: 'render_404'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/campus_life.rb
class CampusLife < ApplicationRecord
  mount_uploader :campus_image1, CampusImage1Uploader
  mount_uploader :campus_image2, CampusImage2Uploader
end

app/models/campus_rank.rb
class CampusRank < ApplicationRecord
end

app/models/capacity.rb
class Capacity < ApplicationRecord
  mount_uploader :capa_image1, CapaImage1Uploader
  mount_uploader :capa_image2, CapaImage2Uploader
  mount_uploader :capa_image3, CapaImage3Uploader
  mount_uploader :capa_image4, CapaImage4Uploader
  mount_uploader :capa_image5, CapaImage5Uploader
  mount_uploader :capa_image6, CapaImage6Uploader
end

app/models/circle_rank.rb
class CircleRank < ApplicationRecord
end

app/models/date_place.rb
class DatePlace < ApplicationRecord
  mount_uploader :place_image, PlaceImageUploader
end

app/models/exam.rb
class Exam < ApplicationRecord
  mount_uploader :exam_image, ExamImageUploader
end

app/models/friend.rb
class Friend < ApplicationRecord
  mount_uploader :friend_photo1, FriendPhoto1Uploader
  mount_uploader :friend_photo2, FriendPhoto2Uploader
  mount_uploader :friend_photo3, FriendPhoto3Uploader
  mount_uploader :friend_photo4, FriendPhoto4Uploader
end

app/models/job_rank.rb
class JobRank < ApplicationRecord
end

app/models/language.rb
class Language < ApplicationRecord
  mount_uploader :image, ImageUploader
end

app/models/life_page.rb
class LifePage < ApplicationRecord
  mount_uploader :life_photo1, LifePhoto1Uploader
  mount_uploader :life_photo2, LifePhoto2Uploader
  mount_uploader :life_photo3, LifePhoto3Uploader
  mount_uploader :life_photo4, LifePhoto4Uploader
end

app/models/love.rb
class Love < ApplicationRecord
  mount_uploader :image1, Image1Uploader
  mount_uploader :image2, Image2Uploader
  mount_uploader :image3, Image3Uploader
  mount_uploader :image4, Image4Uploader
end

app/models/map_url.rb
class MapUrl < ApplicationRecord
end

app/models/men_snap.rb
class MenSnap < ApplicationRecord
  mount_uploader :men_image, MenImageUploader
  mount_uploader :men_image2, MenImage2Uploader
  mount_uploader :men_image3, MenImage3Uploader
end

app/models/ori_page.rb
class OriPage < ApplicationRecord
  mount_uploader :ori_photo1, OriPhoto1Uploader
  mount_uploader :ori_photo2, OriPhoto2Uploader
end

app/models/school_rank.rb
class SchoolRank < ApplicationRecord
end

app/models/trip_rank.rb
class TripRank < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password 
end

app/models/women_snap.rb
class WomenSnap < ApplicationRecord
  mount_uploader :women_image, WomenImageUploader
  mount_uploader :women_image2, WomenImage2Uploader
  mount_uploader :women_image3, WomenImage3Uploader
end

app/models/word.rb
class Word < ApplicationRecord
end

app/controllers/campus_ranks_controller.rb
class CampusRanksController < ApplicationController
  layout 'admin'
  before_action :login_check, only: %i(index new edit create update destroy)
  before_action :set_campus_rank, only: [:show, :edit, :update, :destroy]

  # GET /campus_ranks
  # GET /campus_ranks.json
  def index
    @campus_ranks = CampusRank.all
    @campus_lives = CampusLife.all
  end

  # GET /campus_ranks/1
  # GET /campus_ranks/1.json
  def show
  end

  # GET /campus_ranks/new
  def new
    @campus_rank = CampusRank.new
  end

  # GET /campus_ranks/1/edit
  def edit
  end

  # POST /campus_ranks
  # POST /campus_ranks.json
  def create
    @campus_rank = CampusRank.new(campus_rank_params)

    respond_to do |format|
      if @campus_rank.save
        format.html { redirect_to campus_ranks_path, notice: 'Campus rank was successfully created.' }
        format.json { render :show, status: :created, location: @campus_rank }
      else
        format.html { render :new }
        format.json { render json: @campus_rank.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /campus_ranks/1
  # PATCH/PUT /campus_ranks/1.json
  def update
    respond_to do |format|
      if @campus_rank.update(campus_rank_params)
        format.html { redirect_to campus_ranks_path, notice: 'Campus rank was successfully updated.' }
        format.json { render :show, status: :ok, location: @campus_rank }
      else
        format.html { render :edit }
        format.json { render json: @campus_rank.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /campus_ranks/1
  # DELETE /campus_ranks/1.json
  def destroy
    @campus_rank.destroy
    respond_to do |format|
      format.html { redirect_to campus_ranks_path, notice: 'Campus rank was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_campus_rank
      @campus_rank = CampusRank.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def campus_rank_params
      params.require(:campus_rank).permit(:question,:rank1, :rank2, :rank3)
    end
    def login_check
      if session[:user_id].nil?
        redirect_to sessions_path
      end
    end
end

app/helpers/campus_ranks_helper.rb
module CampusRanksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/views/campus_ranks/_form.html.erb
<%= form_with(model: campus_rank, local: true) do |form| %>
  <% if campus_rank.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(campus_rank.errors.count, "error") %> prohibited this campus_rank from being saved:</h2>

      <ul>
      <% campus_rank.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :rank1 %>
    <%= form.text_field :rank1, id: :campus_rank_rank1 %>
  </div>

  <div class="field">
    <%= form.label :rank2 %>
    <%= form.text_field :rank2, id: :campus_rank_rank2 %>
  </div>

  <div class="field">
    <%= form.label :rank3 %>
    <%= form.text_field :rank3, id: :campus_rank_rank3 %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/campus_ranks/edit.html.erb
<div class="col-md-12">
  <h3>ランキング</h3>
</div>
<div>
  <%=form_for @campus_rank do |f| %>
  <div class="col-md-6 adBox">
    <table class="table">
      <tr>
        <th scope="row">質問</th>
        <td><%= f.text_field :question ,class:"form-control"%></td>
      </tr>
      <tr>
        <th scope="row">1位</th>
        <td><%= f.text_field :rank1 ,class:"form-control"%></td>
      </tr>
      <tr>
        <th scope="row">2位</th>
        <td><%= f.text_field :rank2 ,class:"form-control"%></td>
      </tr>
      <tr>
        <th scope="row">3位</th>
        <td><%= f.text_field :rank3 ,class:"form-control"%></td>
      </tr>
    </table>
    <%= f.submit "送信" ,class: "btn button" %>
  </div>
  <% end %>
</div>

app/views/campus_ranks/index.html.erb
<h3>新歓期の過ごし方</h3>
<div class="col-md-5 adBox">
  <h4>ランキング</h4>
  <% @campus_ranks.each do |obj| %>
    <table class="table">
      <tr>
        <th scope="row">質問</th>
        <td><%= obj.question %><span class="button"><%= link_to '削除',campus_rank_path(obj.id),method: :delete%></span>
        <span class="button"><%= link_to '編集',edit_campus_rank_path(obj.id)%></td>
      </tr>
      <tr>
        <th scope="row">1位</th>
        <td><%= obj.rank1 %></td>
      </tr>
      <tr>
        <th scope="row">2位</th>
        <td><%= obj.rank2 %></td>
      </tr>
      <tr>
        <th scope="row">3位</th>
        <td><%= obj.rank3 %></td>
      </tr>
    </table>
  <%end%>
  <%= link_to '新規作成',new_campus_rank_path%>
</div>
<div class="col-md-6 adBox">
  <h4>素材画像</h4>
  <% @campus_lives.each do |obj| %>
    <table class="table">
      <tr>
        <th scope="row">グラフ1</th>
        <td><%= image_tag obj.campus_image1,class:"resize"%><span class="button"></span>
        <span class="button"><%= link_to '編集',edit_campus_life_path(obj.id)%></td>
      </tr>
      <tr>
        <th scope="row">グラフ2</th>
        <td><%= image_tag obj.campus_image2,class:"resize"%></td>
      </tr>
    </table>
  <%end%>å
</div>

app/views/campus_ranks/new.html.erb
<div class="col-md-12">
  <h3>ランキング</h3>
</div>
<div>
  <%=form_for @campus_rank do |f| %>
  <div class="col-md-6 adBox">
    <table class="table">
      <tr>
        <th scope="row">質問</th>
        <td><%= f.text_field :question ,class:"form-control"%></td>
      </tr>
      <tr>
        <th scope="row">1位</th>
        <td><%= f.text_field :rank1 ,class:"form-control"%></td>
      </tr>
      <tr>
        <th scope="row">2位</th>
        <td><%= f.text_field :rank2 ,class:"form-control"%></td>
      </tr>
      <tr>
        <th scope="row">3位</th>
        <td><%= f.text_field :rank3 ,class:"form-control"%></td>
      </tr>
    </table>
    <%= f.submit "送信" ,class: "btn button" %>
  </div>
  <% end %>
</div>

app/views/campus_ranks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Rank1:</strong>
  <%= @campus_rank.rank1 %>
</p>

<p>
  <strong>Rank2:</strong>
  <%= @campus_rank.rank2 %>
</p>

<p>
  <strong>Rank3:</strong>
  <%= @campus_rank.rank3 %>
</p>

<%= link_to 'Edit', edit_campus_rank_path(@campus_rank) %> |
<%= link_to 'Back', campus_ranks_path %>