config/routes.rb
Rails.application.routes.draw do
  resources :friends
  resources :life_rankings
  resources :life_pages
  resources :advertisements
  get 'ori_event_page/index'
  get 'ori_event_page/:id', to: 'ori_event_page#show'


  resources :ori_pages
  get 'unisna/index'
  get 'unisna/men/:id', to: 'unisna#men'
  get 'unisna/women/:id', to: 'unisna#women'

  resources :map_urls
  get 'dosihsha_ranks/index'

  get 'maps/kyotanabe'
  get 'maps/imadegawa'
  get 'maps/index'
  get 'maps/karasuma'
  get 'maps/kanbaikan'
  get 'maps/shinmachi'

  get 'advices/capacities'
  get 'advices/languages'
  get 'advices/words'
  get 'advices/exams'
  get 'advices/welcome'
  get 'advices/loves'
  get 'advices/life'
  get 'advices/friend'

  resources :women_snaps
  resources :men_snaps
  resources :fashion_ranks
  resources :trip_ranks
  resources :school_ranks
  resources :job_ranks
  resources :circle_ranks
  resources :exam_comments
  resources :exams
  resources :campus_ranks
  resources :campus_lives
  resources :capacities
  resources :date_places
  resources :loves
  resources :languages
  resources :words
  resources :university_words
  resources :introduce_university_words
  resources :sessions
  get 'adminpages/index'
  get 'advices/index'
  root to: 'home#index'
  get '*path', controller: 'application', action: 'render_404'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/campus_life.rb
class CampusLife < ApplicationRecord
  mount_uploader :campus_image1, CampusImage1Uploader
  mount_uploader :campus_image2, CampusImage2Uploader
end

app/models/campus_rank.rb
class CampusRank < ApplicationRecord
end

app/models/capacity.rb
class Capacity < ApplicationRecord
  mount_uploader :capa_image1, CapaImage1Uploader
  mount_uploader :capa_image2, CapaImage2Uploader
  mount_uploader :capa_image3, CapaImage3Uploader
  mount_uploader :capa_image4, CapaImage4Uploader
  mount_uploader :capa_image5, CapaImage5Uploader
  mount_uploader :capa_image6, CapaImage6Uploader
end

app/models/circle_rank.rb
class CircleRank < ApplicationRecord
end

app/models/date_place.rb
class DatePlace < ApplicationRecord
  mount_uploader :place_image, PlaceImageUploader
end

app/models/exam.rb
class Exam < ApplicationRecord
  mount_uploader :exam_image, ExamImageUploader
end

app/models/friend.rb
class Friend < ApplicationRecord
  mount_uploader :friend_photo1, FriendPhoto1Uploader
  mount_uploader :friend_photo2, FriendPhoto2Uploader
  mount_uploader :friend_photo3, FriendPhoto3Uploader
  mount_uploader :friend_photo4, FriendPhoto4Uploader
end

app/models/job_rank.rb
class JobRank < ApplicationRecord
end

app/models/language.rb
class Language < ApplicationRecord
  mount_uploader :image, ImageUploader
end

app/models/life_page.rb
class LifePage < ApplicationRecord
  mount_uploader :life_photo1, LifePhoto1Uploader
  mount_uploader :life_photo2, LifePhoto2Uploader
  mount_uploader :life_photo3, LifePhoto3Uploader
  mount_uploader :life_photo4, LifePhoto4Uploader
end

app/models/love.rb
class Love < ApplicationRecord
  mount_uploader :image1, Image1Uploader
  mount_uploader :image2, Image2Uploader
  mount_uploader :image3, Image3Uploader
  mount_uploader :image4, Image4Uploader
end

app/models/map_url.rb
class MapUrl < ApplicationRecord
end

app/models/men_snap.rb
class MenSnap < ApplicationRecord
  mount_uploader :men_image, MenImageUploader
  mount_uploader :men_image2, MenImage2Uploader
  mount_uploader :men_image3, MenImage3Uploader
end

app/models/ori_page.rb
class OriPage < ApplicationRecord
  mount_uploader :ori_photo1, OriPhoto1Uploader
  mount_uploader :ori_photo2, OriPhoto2Uploader
end

app/models/school_rank.rb
class SchoolRank < ApplicationRecord
end

app/models/trip_rank.rb
class TripRank < ApplicationRecord
end

app/models/university_word.rb
class UniversityWord < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password 
end

app/models/women_snap.rb
class WomenSnap < ApplicationRecord
  mount_uploader :women_image, WomenImageUploader
  mount_uploader :women_image2, WomenImage2Uploader
  mount_uploader :women_image3, WomenImage3Uploader
end

app/models/word.rb
class Word < ApplicationRecord
end

app/controllers/university_words_controller.rb
class UniversityWordsController < ApplicationController
  layout 'admin'
  before_action :login_check, only: %i(index new edit create update destroy)
  before_action :set_universityWord, only: [:show,:update,:edit,:destroy]

  #index->データの一覧の表示
  def index
   #mythreadのデータの全件取得
   @universityWords = UniversityWord.all
   @introduceUniversityWords = IntroduceUniversityWord.all
  end
  #show->個別データの表示
  def show
  #before_actionでデータの取得は完了している
  end

  #new->新規作成ページの表示
  def new
   #モデルオブジェクトの生成
   @universityWords = UniversityWord.new
  end

  #create->新規データの登録
  def create
   #formのデータを受け取る
   @universityWords =UniversityWord.create(universityWords_params)
   #saveメソッドでデータをセーブ　*newメソッド + saveメソッド = createメソッド
   if @universityWords.save
     #saveが完了したら、一覧ページへリダイレクト
     redirect_to university_words_path
   else
     #saveを失敗すると新規作成ページへ
     render 'new'
   end
  end

  #edit->編集ページの表示
  def edit
  #before_actionでデータの取得は完了している
  end

  #update->編集のアップデート
  def update
   #編集データの取得
   if @universityWords.update(universityWords_params)
     #updateが完了したら一覧ページへリダイレクト
     redirect_to university_words_path
   else
     #updateを失敗すると編集ページへ
     render 'edit'
   end
  end

  #destroy->データの削除
  def destroy
   #データの削除
    @universityWords.destroy
   #一覧ページへリダイレクト
   redirect_to university_words_path
  end

  private
  #strong parameters リクエストパラメターの検証（これがないとうまくいかないので注意）
    def universityWords_params
     params.require(:university_word).permit(:rank1, :rank2, :rank3)
    end

    #共通処理なので、before_actionで呼び出している
    def set_universityWord
    #特定データの取得
     @universityWords = UniversityWord.find(params[:id])
    end

    def login_check
      if session[:user_id].nil?
        redirect_to sessions_path
      end
    end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/university_words_helper.rb
module UniversityWordsHelper
end

app/views/university_words/edit.html.erb
<div class="col-md-10">
  <h3>よく使われる用語</h3>
</div>
  <%=form_for @universityWords do |f| %>
  <div class="col-md-6 adBox">
    <table class="table">
      <tr>
        <th scope="row">1位</th>
        <td><%= f.text_field :rank1 ,class:"form-control"%></td>
      </tr>
      <tr>
        <th scope="row">2位</th>
        <td><%= f.text_field :rank2 ,class:"form-control"%></td>
      </tr>
      <tr>
        <th scope="row">3位</th>
        <td><%= f.text_field :rank3 ,class:"form-control"%></td>
      </tr>
    </table>
    <%= f.submit "送信" ,class: "btn" %>
  </div>
  <% end %>

app/views/university_words/index.html.erb
<h3>大学生の用語集</h3>
<div class="col-md-5 adBox">
  <h4>よく使われる用語</h4>
  <% @universityWords.each do |obj| %>
    <table class="table">
      <tr>
        <th scope="row">1位</th>
        <td><%= obj.rank1 %>
        <span class="button"><%= link_to '編集',edit_university_word_path(obj.id)%></td>
      </tr>
      <tr>
        <th scope="row">2位</th>
        <td><%= obj.rank2 %></td>
      </tr>
      <tr>
        <th scope="row">3位</th>
        <td><%= obj.rank3 %></td>
      </tr>
    </table>
  <%end%>

</div>
<div class="col-md-6 adBox">
  <h4>用語説明</h4>
  <% @introduceUniversityWords.each do |obj| %>
    <table class="table">
      <tr>
        <th class="col-md-3" scope="row">用語名</th>
        <td class="col-md-9"><%= obj.title %><span class="button"><%= link_to '削除',introduce_university_word_path(obj.id),method: :delete%></span>
        <span class="button"><%= link_to '編集',edit_introduce_university_word_path(obj.id)%></td>
      </tr>
      <tr>
        <th scope="row">意味</th>
        <td><%= obj.meaning %></td>
      </tr>
      <tr>
        <th scope="row" >例文</th>
        <td><%= obj.example%></td>
      </tr>
    </table>
  <%end%>
  <%= link_to '新規作成',new_introduce_university_word_path%>
</div>

app/views/university_words/new.html.erb
<%=form_for @universityWords do |f| %>
  <%= f.text_field :rank1 %>
  <%= f.text_field :rank2 %>
  <%= f.text_field :rank3 %>
  <%= f.submit "send" %>
<% end %>